### ISSUE TITLE
Consider usage of F-strings

### ISSUE THREAD

**Issue by kiplingw** [joelvpayne/canlii-pdfetch#1]
Suggestion to upstream to consider using [F strings](https://realpython.com/python-f-strings/) instead of [this](https://github.com/joelvpayne/canlii-pdfetch/blob/074a69de2b58aa7ad66924acebb693cb7742fa57/canlii-pdfetch.py#L21). This will also help make your strings more easily translatable.

**Comment by joelvpayne** [comment]
Thanks for the tip! Fixed and pushed.
